export const API_CONFIG = {
  BASE_URL: 'http://192.168.1.6:3000',
  
  ENDPOINTS: {
    PAYMENTS: '/api/payments',
    AUTH: '/api/auth',
    USERS: '/api/users',
    NOTIFICATIONS: '/api/notifications',
    FINES: '/api/fines',
    MANUAL_REGISTRATION: '/api/manual-registration',
    PARKING_SPACES: '/api/parking-spaces',
  },
  
  TIMEOUT: 10000,
};

export const API_URLS = {
  PAYMENTS: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.PAYMENTS}`,
  AUTH: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.AUTH}`,
  USERS: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.USERS}`,
  NOTIFICATIONS: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.NOTIFICATIONS}`,
  FINES: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.FINES}`,
  MANUAL_REGISTRATION: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.MANUAL_REGISTRATION}`,
  PARKING_SPACES: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.PARKING_SPACES}`,
};